<a href="https://colab.research.google.com/github/yurimmmmmm/Python_Data_Analysis_and_Image_Processing/blob/main/Numpy%EC%9D%98_%EC%97%B0%EC%82%B0%EA%B3%BC_%ED%95%A8%EC%88%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 기본적인 Numpy 상수 연산

import numpy as np

array = np.random.randint(1, 10, size=4)
array1 = np.random.randint(1, 10, size=4).reshape(2,2)
print(array)
print(array.reshape(2,2))
print('\n', array1)

result_array = array * 10
print('\n', result_array)

[1 9 8 3]
[[1 9]
 [8 3]]

 [[5 9]
 [2 7]]

 [10 90 80 30]


In [2]:
# 서로 다른 형태의 Numpy 연산

array2 = np.arange(4).reshape(2, 2)
array3 = np.arange(2)

print(array2)
print(array3)
print(array2 + array3)

[[0 1]
 [2 3]]
[0 1]
[[0 2]
 [2 4]]


In [3]:
array5 = np.arange(0, 8).reshape(2, 4)
array6 = np.arange(0, 8).reshape(2, 4)
array7 = np.concatenate([array5, array6], axis=0)
array8 = np.arange(0, 4).reshape(4, 1)
array9 = np.arange(8).reshape(2, 4)



print('\n', array5)
print('\n', array6)
print('\n', array9)
print('\n', array7)
print('\n', array8)
print('\n', array7 + array8)


 [[0 1 2 3]
 [4 5 6 7]]

 [[0 1 2 3]
 [4 5 6 7]]

 [[0 1 2 3]
 [4 5 6 7]]

 [[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]
 [4 5 6 7]]

 [[0]
 [1]
 [2]
 [3]]

 [[ 0  1  2  3]
 [ 5  6  7  8]
 [ 2  3  4  5]
 [ 7  8  9 10]]


In [4]:
# Numpy의 마스킹 연산

array10 = np.arange(16).reshape(4, 4)
print('\n', array10)

array11 = array10 < 10
print('\n', array11)

array10[array11] = 100
print('\n', array10)


 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

 [[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]
 [False False False False]]

 [[100 100 100 100]
 [100 100 100 100]
 [100 100  10  11]
 [ 12  13  14  15]]


In [5]:
# Numpy의 다양한 집계 함수

array20 = np.arange(16).reshape(4, 4)

print(array20, '\n')
print("최대값:", np.max(array20))
print("최소값:", np.min(array20))
print("합계:", np.sum(array20))
print("평균값:", np.mean(array20))
print("열 별 합계:", np.sum(array20, axis = 0))
print("행 별 합계:", np.sum(array20, axis = 1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

최대값: 15
최소값: 0
합계: 120
평균값: 7.5
열 별 합계: [24 28 32 36]
행 별 합계: [ 6 22 38 54]
