<a href="https://colab.research.google.com/github/yurimmmmmm/Python_Data_Analysis_and_Image_Processing/blob/main/Numpy%EC%9D%98_%ED%99%9C%EC%9A%A9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# 단일 객체 저장 및 불러오기

array = np.arange(0, 10)
np.save('saved.npy', array)
array = np.load('saved.npy')
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
# 복수 객체 저장 및 불러오기

array1 = np.arange(0, 10)
array2 = np.arange(10, 20)
np.savez('saved.npz', array1=array1, array2=array2)
data = np.load('saved.npz')
result1 = data['array1']
result2 = data['array2']

print(result1)
print(result2)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [13]:
# Numpy 원소 오름차순 정렬

array3 = np.array([5, 9, 10, 3 ,1])
print(array3)
array3.sort()
print(array3)

# 내림차순순
print(array3[::-1])
#array4 = array3.sort()
#print(array4)

[ 5  9 10  3  1]
[ 1  3  5  9 10]
[10  9  5  3  1]


In [20]:
# 각 열을 기준으로 정렬

array5 = np.array([[5, 9, 10, 3, 1], [8, 3, 4, 2 ,5]])
print(array5)
array5.sort(axis=0)
print(array5)

[[ 5  9 10  3  1]
 [ 8  3  4  2  5]]
[[ 5  3  4  2  1]
 [ 8  9 10  3  5]]


In [22]:
# 균일한 간격으로 데이터 생성

array6 = np.linspace(0, 10, 5)
print(array6)

[ 0.   2.5  5.   7.5 10. ]


In [28]:
#난수의 재연 (실행마다 결과 동일)

np.random.seed(7)
array7 = np.random.randint(0, 10, (2, 3))
print(array7)

[[4 9 6]
 [3 3 7]]


In [31]:
# Numpy 배열 객체 복사

'''array8 = np.arange(0, 10)
array9 = array8
array9[0] = 100
print(array8)'''

array8 = np.arange(0, 10)
array9 = array8.copy()
array9[0] = 100
print(array8)
print(array9)

[0 1 2 3 4 5 6 7 8 9]
[100   1   2   3   4   5   6   7   8   9]


In [32]:
# 중복된 원소 제거

array10 = np.array([1, 1, 2, 2, 3, 3, 4])
print(np.unique(array10))

[1 2 3 4]
