<a href="https://colab.research.google.com/github/yurimmmmmm/Python_Data_Analysis_and_Image_Processing/blob/main/Numpy%EC%9D%98_%EA%B8%B0%EB%B3%B8_%EC%82%AC%EC%9A%A9%EB%B2%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

#Python의 Numpy 라이브러리는 List와 상호 변환이 가능
list_data = [1, 2, 3]
array = np.array(list_data)

print(list_data)
print(array)
print(array.size) # 배열의 크기
print(array.dtype) # 배열 원소의 타입
print(array[2]) # 인덱스 2의 원소

[1, 2, 3]
[1 2 3]
3
int64
3


In [3]:
# Python의 Numpy 라이브러리는 다양한 형태의 배열을 초기화 할 수 있음

# 0부터 3까지의 배열 만들기
array1 = np.arange(4)
print(array1)
print(array1.dtype)

# 0으로 초기화
array2 = np.zeros((4, 4), dtype = float)
print('\n', array2)
print(array2.dtype)

array3 = np.zeros((4, 4), dtype = int)
print('\n', array3)
print(array3.dtype)

# 1로 초기화
array4 = np.ones((3, 3), dtype = str)
print('\n', array4)
print(array4.dtype)

[0 1 2 3]
int64

 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
float64

 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int64

 [['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]
<U1


In [4]:
# 0부터 9까지 랜덤하게 초기화 된 배열 만들기
array5 = np.random.randint(0, 10, (3,3))
print(array5)
print(array5.dtype)

[[4 5 3]
 [5 1 4]
 [6 8 4]]
int64


In [5]:
# 평균이 0이고, 표준편차가 1인 표준 정규를 띄는 배열
array6 = np.random.normal(0, 1, (3,3))
print(array6)

[[-2.06009522 -0.04423631  0.8179309 ]
 [ 0.50407122  1.51775973  0.02413602]
 [ 3.29279368 -0.07240089 -0.20435192]]


In [6]:
# Numpy는 다양한 형태로 합치기가 가능 
array7 = np.array([1, 2, 3])
array8 = np.array([4, 5, 6])
array9= np.array([7, 8, 9])

array10 = np.concatenate([array7, array8, array9])

print(array10.size)
print(array10.shape)
print(array10)
print(array10.dtype)

9
(9,)
[1 2 3 4 5 6 7 8 9]
int64


In [7]:
# Numpy의 형태를 변경할 수 있음
array11 = np.array([1, 2, 3, 4])
array12 = array11.reshape((2, 2))

print(array12)
print(array12.size)
print(array12.shape)
print(array12.dtype)

[[1 2]
 [3 4]]
4
(2, 2)
int64


In [8]:
# Numpy를 위 아래로 합칠 수 있음
array13 = np.arange(4).reshape(1, 4)
array14 = np.arange(8).reshape(2, 4)

print(array13)
print(array14, '\n')

array15 = np.concatenate([array13, array14], axis=0)
#array15 = np.concatenate([array13, array14], axis=1)
print(array15, '\n', '\n', '\n')

array16 = np.arange(4).reshape(4, 1)
array17 = np.arange(8).reshape(4, 2)

print(array16, '\n')
print(array17, '\n')

array18 = np.concatenate([array16, array17], axis=1)
#array18 = np.concatenate([array16, array17], axis=0)
print(array18)

[[0 1 2 3]]
[[0 1 2 3]
 [4 5 6 7]] 

[[0 1 2 3]
 [0 1 2 3]
 [4 5 6 7]] 
 
 

[[0]
 [1]
 [2]
 [3]] 

[[0 1]
 [2 3]
 [4 5]
 [6 7]] 

[[0 0 1]
 [1 2 3]
 [2 4 5]
 [3 6 7]]


In [9]:
# Numpy의 형태를 나누기 할 수 있음
array19 = np.arange(8).reshape(2, 4)
left, right = np.split(array19, [2], axis=0)
left1, right1 = np.split(array19, [2], axis=1)
print(array19)
print('\n',left)
print(right)
print('\n', left.shape, right.shape)

print('\n',left1)
print(right1)
print('\n', left1.shape, right1.shape)

[[0 1 2 3]
 [4 5 6 7]]

 [[0 1 2 3]
 [4 5 6 7]]
[]

 (2, 4) (0, 4)

 [[0 1]
 [4 5]]
[[2 3]
 [6 7]]

 (2, 2) (2, 2)
